notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - python setup.py build_ext
  - python setup.py bdist_wheel
  - python setup.py install
after_success:
  - python tests/test_itensor.py -v
matrix:
  include:
    - os: linux
      language: python
      python: "3.3"
      addons: &linux_addon
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7', 'liblapack-dev', 'libopenblas-dev']
      before_install:
        - python -m pip install --upgrade pip setuptools wheel
      env: CC=gcc-7 CXX=g++-7
    - os: linux
      language: python
      python: "3.4"
      addons: *linux_addon
      before_install:
        - python -m pip install --upgrade pip setuptools wheel
      env: CC=gcc-7 CXX=g++-7
    - os: linux
      language: python
      python: "3.5"
      addons: *linux_addon
      before_install:
        - python -m pip install --upgrade pip setuptools wheel
      env: CC=gcc-7 CXX=g++-7
    - os: linux
      language: python
      python: "3.6"
      addons: *linux_addon
      before_install:
        - python -m pip install --upgrade pip setuptools wheel
      env: CC=gcc-7 CXX=g++-7
    - os: osx
      language: generic
      before_install:
        - brew update
        - brew outdated pyenv || brew upgrade pyenv
        - brew install pyenv-virtualenv
        - pyenv install 3.6.4
        - export PYENV_VERSION=3.6.4
        - eval "$(pyenv virtualenv-init -)"
        - pyenv virtualenv venv
        - pyenv shell venv
        - which python
        - python --version
        - python -m pip install --upgrade pip setuptools wheel
      env:
        - CC=clang CXX=clang++
